# Prometheus配置文件 - 任务管理服务监控

global:
  scrape_interval: 15s     # 全局抓取间隔
  evaluation_interval: 15s # 规则评估间隔

  # 外部标签，将被添加到所有时间序列和告警中
  external_labels:
    monitor: 'task-manager-monitor'

# 规则文件
rule_files:
  - "rules/*.yml"

# 抓取配置
scrape_configs:
  # Prometheus自监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 任务管理服务
  - job_name: 'task-manager-service'
    static_configs:
      - targets: ['task-manager:8084']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: http

  # PostgreSQL监控 (如果启用了postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis监控 (如果启用了redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node Exporter (系统监控)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 存储配置
storage:
  tsdb:
    path: /prometheus
    retention.time: 7d
    retention.size: 10GB

# Web配置
web:
  console:
    libraries:
      - /etc/prometheus/console_libraries
    templates:
      - /etc/prometheus/consoles
  
  # 启用生命周期API
  enable-lifecycle: true
  
  # 启用管理API
  enable-admin-api: true