# Prometheus配置文件
# Message Push Service监控配置

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'message-push-monitor'

# 规则文件
rule_files:
  - "alert_rules.yml"

# 监控目标配置
scrape_configs:
  # Message Push Service监控
  - job_name: 'message-push-service'
    static_configs:
      - targets: ['message-push-service:9090']
    scrape_interval: 10s
    metrics_path: '/sse/metrics'
    scheme: http
    
  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s
    
  # Nginx监控
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    scrape_interval: 15s
    metrics_path: '/nginx_status'
    
  # 系统监控
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 远程写入配置 (可选)
# remote_write:
#   - url: "http://your-remote-storage:8086/api/v1/prom/write"